spring:
  datasource:
    url: jdbc:mariadb://schedulemaker.cwkzykfbidqz.us-east-2.rds.amazonaws.com:3306/ScheduleMaker
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ghdud1230

jwt:
  secret: "FlyingFishermanScheduleMakerCode"

---

spring:
  profiles: develop
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/ScheduleMaker
    username: sa
    password:

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: "FlyingFishermanScheduleMakerCode"
spring.devtools.livereload.enabled: true

---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://schedulemaker.cwkzykfbidqz.us-east-2.rds.amazonaws.com:3306/ScheduleMaker
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ghdud1230

---

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/ScheduleMaker
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ghdud1230