spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ScheduleMaker
    username: root
    password: ghdud1230

jwt:
  secret: "FlyingFishermanScheduleMakerCode"

---

spring:
  profiles: develop
  datasource:
    url: jdbc:h2:~/data/demo

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    freemaker:
      cache: false

jwt:
  secret: "FlyingFishermanScheduleMakerCode"

spring.devtools.livereload.enabled: true
